config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      post :publish
      post :hide
    end
    collection do
      get :my_articles
      get :search
    end
    resources :comments
  end
  resources :tags
  resources :categories
  root "articles#index"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  attr_accessor :tag_list

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :tags
  belongs_to :category
  has_many :comments, dependent: :destroy
  
  mount_uploader :cover, CoverUploader

  validates :title, presence: true
  
  def toggle_published!
    self.published = !published
    save
  end

  def self.search_published(query)
    self.search({
      query: {
        bool: {
          must: [
          {
            multi_match: {
              query: query,
              fields: [:title, :description]
            }
          },
          {
            match: {
              published: true
            }
          }]
        }
      }
    })
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :articles
	validates :name, presence: true, uniqueness: { case_sensitive: false }

  before_save :normalize_name

  private

  def normalize_name
    self.name = name.downcase
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable, :confirmable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         confirm_within: 3.days, # Change the time window for confirming an account (default is 2 days)
         reconfirmable: true, # Allow users to re-confirm their email address if they change it
         confirmation_keys: [:email]

  mount_uploader :avatar, AvatarUploader
  has_many :articles, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy

  def mailer
    UserMailer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.where(published: true)
  end

  def my_articles
    @articles = current_user.articles.all
  end

  def show
    @comments = @article.comments.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def publish
    @article = Article.find(params[:id])
    @article.update(published: true)
    redirect_to articles_url, notice: 'Article was successfully published.'
  end

  def hide
    @article = Article.find(params[:id])
    @article.update(published: false)
    redirect_to articles_url, notice: 'Article was successfully hidden.'
  end

  def search
    query = params[:search_articles].presence && params[:search_articles][:query]

    if query
      @articles = Article.search_published(query)
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :cover,  :category_id,  :published, tag_ids: [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article, notice: 'Comment was successfully created.'
    else
      redirect_to @article, alert: 'Failed to create comment.'
    end
  end

  private

	def comment_params
	  params.require(:comment).permit(:value)
	end
	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div class="article">

<%= image_tag(article.cover.url, size: "300x200") if article.cover.present? %>
  <h2><%= link_to article.title, article %></h2>
  <p>Description: <%= article.description %></p>
  <p>Tag: <% article.tags.each do |tag| %>
    <%= tag.name %>
  <% end %></p>
  <p>Category: <%= article.category.name %></p>
  <p>Author: <%= article.author.email %></p>
  <p>Posted <%= time_ago_in_words(article.created_at) %> ago</p>
  <% if article.author == current_user && article.published %>
    <%= form_with model: article, url: hide_article_path(article), method: :post do |form| %>
      <%= form.submit 'Hide' %>
    <% end %>
  <% elsif article.author == current_user && !article.published %>
    <%= form_with model: article, url: publish_article_path(article), method: :post do |form| %>
      <%= form.submit 'Publish' %>
    <% end %>
  <% end %><br>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description, id: :article_description %>
  </div>

  <div class="field">
    <%= form.label :cover %><br />
    <%= form.file_field :cover %>
  </div>

<div class="field">
  <%= form.label :tag %><br>
  <% Tag.all.each do |tag| %>
    <label>
      <%= check_box_tag "article[tag_ids][]", tag.id, @article&.tag_ids&.include?(tag.id) %>
      <%= tag.name %>
    </label>
  <% end %>
</div>

  <div class="field">
    <%= form.label :category %><br />
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

Press <%= link_to 'here', search_articles_path %> to search for Article.

<h1>Articles</h1>

<%= render @articles %>

<br>

<%= link_to 'New Article', new_article_path %> 

app/views/articles/my_articles.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<%= render @articles %>


<br>

<%= link_to 'New Article', new_article_path %> 

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/search.html.erb
<h1>Elastic search for posts</h1>

<%= form_for :search_articles, url: search_articles_path, method: :get do |form| %>
  <%= form.text_field :query, value: params[:search_articles].presence && params[:search_articles][:query] %>
  <%= form.submit 'Search' %>
<% end %>

<% unless @articles.nil? %>
  <% if @articles.empty? %>
    <h2>No articles found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>

    <table class="table">
      <thead>
         <tr>
           <th>Author</th>
           <th>Title</th>
           <th>Description</th>
           <th>Tags</th>
           <th>Category</th>
           <th>Published on</th>
           <th>Actions</th>
           <th>Img</th>
         </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>           
            <td><% author = User.find_by(id: article.author_id) %>
              <%= author.email %>
            </td>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td>  
              <% article.tags.each do |tag| %>
                <%= tag.name %>
              <% end %>  
            </td>
            <td><% category = Category.find_by(id: article.category_id) %>
              <%= category.name %></td>
            <td><%= time_ago_in_words(article.created_at) %> ago</td>

            <td><%= link_to 'View', article_path(article.id) %></td>
            <td><%= image_tag(article.cover.url, size: "300x200") if article.cover.present? %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= image_tag(@article.cover.url, size: "300x200") if @article.cover.present? %>

<p>
  <strong>Tags:</strong>
  <% @article.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
</p>

<p>
  <strong>Category:</strong>
  <%= @article.category.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author.email %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @article.created_at %>
</p>

<% if @article.author == current_user %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %> |
<% end %>
<%= link_to 'Back', articles_path %> 

<div id="comments-container">
  <h2>Comments</h2>
  <% if @comments.any? %>
    <% @comments.each do |comment| %>
      <p>
        <strong>Commenter:</strong>
        <%= comment.user.email %>
      </p>

      <p>
        <strong>Comment:</strong>
        <%= comment.value %>
      </p>
    <% end %>
    <%= paginate @comments %>
  <% end %>
</div>

<h2>Add a comment:</h2>
<%= form_with(model: [@article, @article.comments.build], url: article_path(@article, page: params[:page])) do |form| %>
  <p>
    <%= form.label :value %><br>
    <%= form.text_area :value %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br/>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions"><br/>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
  <div>
    <%= link_to category.name, category_path(category) %>
  </div>
<% end %>
<br>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name, id: :category_name %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginDevise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div id="user_nav">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. This cannot be cheese?
        <%#= button_to("Log Out",destroy_user_session_path,method: :delete) %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> |
        <%= link_to 'Edit Account', edit_user_registration_path %><br/>

        <%= link_to 'Article', articles_path %> |
        <%= link_to 'Category', categories_path %> |
        <%= link_to "Tags", tags_path %> |
        <%= link_to 'My Article', my_articles_articles_path %> 
    <% end %>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" style="color: green;"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>
<%= form_with model: @tag, url: tag_path(@tag), method: :patch do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit "Update Tag" %>
<% end %>
<p><%= link_to "Back to Tag", tag_path(@tag) %> | <%= link_to "Back to All Tags", tags_path %></p>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<% @tags.each do |tag| %>
  <div>
    <%= link_to tag.name, tag_path(tag) %>
  </div>
<% end %>
<br>
<%= link_to "New Tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<%= form_with model: @tag, url: tags_path do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit "Create Tag" %>
<% end %>
<p><%= link_to "Back to All Tags", tags_path %></p>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<p><%= link_to "Edit", edit_tag_path(@tag) %> | <%= link_to "Back to All Tags", tags_path %></p>